[package]
name = "adventofcode_2021"
version = "0.1.0"
edition = "2021"
authors = ["Christopher Leyssen"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
